// Automatically generated by astro-icon
// cf87b270422105ff6e9c67ef3cda7c9447b4bb84141fd5bded980dfa4f1f728f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fa:github"
		| "fa:linkedin"
		| "github-mark-white";
}