// Automatically generated by astro-icon
// 18c51837ef66f0bad077acaf2230ff1ef6641a9ff1797c14715539f48182e49e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fa:github"
		| "fa:instagram"
		| "fa:linkedin"
		| "github-mark-white";
}